"""NMS Tech Proprietary Material. Copyright © 2026 NMS Tech."""
from typing import Optional
from pydantic import BaseModel, Field

class PatientCase(BaseModel):
    age: Optional[int] = Field(default=None, ge=0, le=130)
    sex: str = ""
    pregnancy_status: str = ""
    chief_complaint: str = ""
    duration: str = ""
    history_of_presenting_illness: str = ""
    past_medical_history: str = ""
    past_surgical_history: str = ""
    medication_history: str = ""
    allergy_history: str = ""
    family_history: str = ""
    diet_appetite: str = ""
    sleep: str = ""
    bowel_bladder: str = ""
    smoking: str = ""
    alcohol: str = ""
    substance_use: str = ""
    occupation_exposure: str = ""
    travel_exposure: str = ""
    menstrual_obstetric_history: str = ""
    immunization_history: str = ""
    other_personal_history: str = ""
    vitals: str = ""
    general_examination: str = ""
    cardiovascular_exam: str = ""
    respiratory_exam: str = ""
    abdominal_exam: str = ""
    neurological_exam: str = ""
    musculoskeletal_exam: str = ""
    local_other_exam: str = ""
    cbc: str = ""
    glucose: str = ""
    electrolytes: str = ""
    renal_function: str = ""
    liver_function: str = ""
    coagulation: str = ""
    inflammatory_markers: str = ""
    endocrine_tests: str = ""
    cardiac_biomarkers: str = ""
    abg_vbg: str = ""
    urine_tests: str = ""
    other_blood_tests: str = ""
    blood_culture: str = ""
    urine_culture: str = ""
    sputum_culture: str = ""
    csf_tests_culture: str = ""
    pcr_serology: str = ""
    other_microbiology: str = ""
    biopsy_histopathology: str = ""
    cytology: str = ""
    ecg: str = ""
    xray: str = ""
    ultrasound: str = ""
    ct: str = ""
    mri: str = ""
    mra: str = ""
    mrv: str = ""
    contrast_notes: str = ""
    other_investigations: str = ""

class AnalyzeRequest(BaseModel):
    patient: PatientCase
    question: str = "Provide a prioritized differential diagnosis and next evaluation."
